name: Build and Deploy Documentation

on:
  push:
#    branches: [ "main" ]
#    paths:
#      - 'Documentation~/**'
#      - '.github/workflows/build-docs.yml'
#      - 'LICENSE.md'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important for history and navigation
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Install DocFX
      run: dotnet tool update -g docfx
    
    - name: Build Documentation
      run: |
        cd Documentation~/docfx_project
        docfx metadata
        docfx build
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'Documentation~/docfx_project/_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
